version: '3.8'
services:
  proxy:
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - "6001:6001"
      - "6023:6023"
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    # ports:
    #   - "15672:15672"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"