version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: "host"
    restart: always
  rabbitmq:
    image: rabbitmq:latest
    network_mode: "host"
    restart: always
  proxy:
    build: .
    environment: 
      - APP_PORT=5001
      - AMQP_URI=amqp://127.0.0.1/
      - TARGET_HOST=10.158.0.6
      - TARGET_PORT=5001
    network_mode: "host"
    restart: always
    depends_on:
      - rabbitmq